name: gitleaks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: gitleaks-action checkout(priv)
        uses: actions/checkout@v2
        with:
          repository: GiriRaj249/gitleaks-action
          ref: main
          path: ./action
      - name: run git actions
        uses: ./action
