name: gitleaks
on: [pull_request]

jobs:
  ubuntu:
    name: gitleaks / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run Gitleaks with reviewdog output on the PR
        uses: contentful/action-gitleaks@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: .
          reporter: github-pr-review
          fail_on_error: false
          filter_mode: nofilter
          level: error
