name: gitleaks
on: [pull_request]

jobs:
  ubuntu:
    name: gitleaks / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run Gitleaks with reviewdog output on the PR
        uses: karankohli-cf/action-gitleaks@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: .
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
          level: error
          report_url: "https://github.com/contentful/security-tools-config/issues/new?title=False%20positive%20in%20Gitleaks"
          gitleaks_config: "contentful/security-tools-config/contents/secrets/gitleaks/gitleaks.toml"
