name: kics
on: [pull_request]

jobs:
  ubuntu:
    name: kics / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terrafrom
        working-directory: .
        run: |
          terraform init

      - name: Run kics with reviewdog output on the PR
        uses: karankohli-cf/action-kics@master
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: nofilter
          level: info # Get more output from reviewdog
          reporter: github-pr-review # Change reviewdog reporter
          fail_on_error: true # Fail action if errors are found
