name: kics
on: [pull_request]

jobs:
  ubuntu:
    name: kics / ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terrafrom
        working-directory: .
        run: |
          terraform init
      - name: Run kics with reviewdog output on the PR
        uses: contentful/action-kics@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: .
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
          level: error
          kics_flags: "--exclude-severities info,low,medium,trace --payload-lines --ci"
